import io
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    ListFlowable, ListItem, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors


# ---------------------------------------------------------------------------
# Header / footer canvas callback
# ---------------------------------------------------------------------------

def header_footer(canvas, doc):
    """Draw the InvestAI branding header and a page number footer."""
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 18)
    canvas.setFillColor(colors.HexColor('#FF4B2B'))
    canvas.drawString(doc.leftMargin, doc.pagesize[1] - 0.6 * inch, "InvestAI")

    canvas.setFont('Helvetica', 12)
    canvas.setFillColor(colors.gray)
    canvas.drawString(doc.leftMargin + 85, doc.pagesize[1] - 0.6 * inch, "| Agentic Stock Research")

    canvas.setStrokeColor(colors.HexColor('#2D3748'))
    canvas.setLineWidth(1)
    canvas.line(doc.leftMargin, doc.pagesize[1] - 0.7 * inch,
                doc.pagesize[0] - doc.rightMargin, doc.pagesize[1] - 0.7 * inch)

    canvas.setFont('Helvetica', 9)
    page_num = canvas.getPageNumber()
    canvas.drawString(doc.leftMargin, 0.5 * inch, "Generated by InvestAI Platform")
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.5 * inch, f"Page {page_num}")
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Text sanitisation helpers
# ---------------------------------------------------------------------------

def _sanitise_text(text: str) -> str:
    """
    Replace characters that standard PDF fonts cannot render, then
    escape & so ReportLab's XML mini-parser doesn't choke.
    Order matters: escape & first, then apply tag conversions.
    """
    # Unicode replacements
    replacements = [
        ('₹', 'Rs.'), ('—', '-'), ('–', '-'),
        ('\u2019', "'"), ('\u2018', "'"), ('\u201c', '"'), ('\u201d', '"'),
        ('…', '...'), ('\u2022', '-'), ('\u2013', '-'), ('\u2014', '-'),
        ('\u00b7', '-'), ('\xa0', ' '),
    ]
    for old, new in replacements:
        text = text.replace(old, new)

    # Strip emojis / non-cp1252 chars
    text = text.encode('cp1252', errors='ignore').decode('cp1252')

    # Strip raw HTML tags (LLM leftovers) except ones we handle explicitly
    text = re.sub(r'<br\s*/?>', ' ', text, flags=re.IGNORECASE)
    text = re.sub(r'<b>(.*?)</b>', r'**\1**', text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r'<(?:i|em)>(.*?)</(?:i|em)>', r'_\1_', text, flags=re.IGNORECASE | re.DOTALL)
    text = re.sub(r'<[^>]+>', '', text)

    # Escape & for ReportLab XML (but don't double-escape)
    text = text.replace('&', '&amp;')
    text = re.sub(r'&amp;(amp|lt|gt|nbsp|quot);', r'&\1;', text)

    return text


def _inline_markup(text: str) -> str:
    """Apply bold / italic / code inline markdown → ReportLab XML tags."""
    text = _sanitise_text(text)
    # Bold (**text** or __text__)
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text, flags=re.DOTALL)
    text = re.sub(r'__(.+?)__', r'<b>\1</b>', text, flags=re.DOTALL)
    # Italic (*text* or _text_) — only single markers
    text = re.sub(r'\*([^*\n]+?)\*', r'<i>\1</i>', text)
    text = re.sub(r'(?<![_\w])_([^_\n]+?)_(?![_\w])', r'<i>\1</i>', text)
    # Inline code
    text = re.sub(r'`([^`]+)`', r'<font face="Courier" fontSize="9">\1</font>', text)
    return text


# ---------------------------------------------------------------------------
# Style definitions (built once per call but cheap)
# ---------------------------------------------------------------------------

def _build_styles():
    styles = getSampleStyleSheet()

    def add(name, parent_name, **kwargs):
        if name not in styles:
            styles.add(ParagraphStyle(name=name, parent=styles[parent_name], **kwargs))

    add('H1', 'Heading1',
        fontName='Helvetica-Bold', fontSize=18,
        spaceBefore=18, spaceAfter=10,
        textColor=colors.HexColor('#FF4B2B'),
        leading=22)

    add('H2', 'Heading2',
        fontName='Helvetica-Bold', fontSize=14,
        spaceBefore=14, spaceAfter=6,
        textColor=colors.HexColor('#1A202C'),
        leading=18)

    add('H3', 'Heading3',
        fontName='Helvetica-Bold', fontSize=12,
        spaceBefore=10, spaceAfter=4,
        textColor=colors.HexColor('#4A5568'),
        leading=16)

    add('H4', 'Heading3',
        fontName='Helvetica-Bold', fontSize=11,
        spaceBefore=8, spaceAfter=3,
        textColor=colors.HexColor('#718096'),
        leading=14)

    add('Body', 'Normal',
        fontName='Helvetica', fontSize=10,
        spaceAfter=6, leading=14,
        textColor=colors.HexColor('#1A202C'))

    add('Bullet', 'Normal',
        fontName='Helvetica', fontSize=10,
        spaceAfter=2, leading=13,
        leftIndent=12,
        textColor=colors.HexColor('#1A202C'))

    add('SubBullet', 'Normal',
        fontName='Helvetica', fontSize=9,
        spaceAfter=2, leading=12,
        leftIndent=24,
        textColor=colors.HexColor('#4A5568'))

    add('Code', 'Normal',
        fontName='Courier', fontSize=9,
        spaceAfter=4, leading=12,
        textColor=colors.HexColor('#2D3748'),
        backColor=colors.HexColor('#F7FAFC'))

    add('TableHeader', 'Normal',
        fontName='Helvetica-Bold', fontSize=9,
        textColor=colors.HexColor('#1A202C'),
        leading=12)

    add('TableCell', 'Normal',
        fontName='Helvetica', fontSize=9,
        textColor=colors.HexColor('#1A202C'),
        leading=12)

    return styles


# ---------------------------------------------------------------------------
# Table parser
# ---------------------------------------------------------------------------

def _parse_table(lines: list, styles) -> Table | None:
    """
    Parse a list of raw markdown table lines into a ReportLab Table.
    Returns None if parsing fails.
    """
    data = []
    is_header_row = True
    for line in lines:
        line = line.strip()
        # Separator row (---|---|---) → marks end of header
        if re.match(r'^[\s|:\-]+$', line):
            is_header_row = False
            continue
        if not line or not '|' in line:
            continue
        # Strip outer pipes
        if line.startswith('|'):
            line = line[1:]
        if line.endswith('|'):
            line = line[:-1]
        cells = [c.strip() for c in line.split('|')]
        if not any(cells):
            continue
        style = styles['TableHeader'] if data == [] else styles['TableCell']
        data.append([Paragraph(_inline_markup(c), style) for c in cells])

    if len(data) < 1:
        return None

    num_cols = max(len(row) for row in data)
    # Pad short rows
    for row in data:
        while len(row) < num_cols:
            row.append(Paragraph('', styles['TableCell']))

    # Compute column widths: distribute available width evenly
    page_w = letter[0] - 2 * inch   # usable width
    col_w = page_w / num_cols

    t = Table(data, colWidths=[col_w] * num_cols, repeatRows=1)
    t.setStyle(TableStyle([
        # Header row
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#EBF4FF')),
        ('FONTNAME',   (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0, 0), (-1, 0), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 7),
        ('TOPPADDING',    (0, 0), (-1, 0), 7),
        # Data rows — alternating
        ('BACKGROUND', (0, 1), (-1, -1), colors.white),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1),
         [colors.white, colors.HexColor('#F7FAFC')]),
        # All cells
        ('ALIGN',   (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN',  (0, 0), (-1, -1), 'TOP'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('TOPPADDING',    (0, 1), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 5),
        ('LEFTPADDING',  (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        # Grid
        ('GRID',    (0, 0), (-1, -1), 0.4, colors.HexColor('#CBD5E0')),
        ('LINEBELOW', (0, 0), (-1, 0), 1.5, colors.HexColor('#90CDF4')),
    ]))
    return t


# ---------------------------------------------------------------------------
# Main generator — line-by-line state machine
# ---------------------------------------------------------------------------

def generate_pdf_report(markdown_text: str) -> bytes:
    """
    Parse markdown line-by-line and produce a well-formatted PDF.
    Handles: H1-H4, bullet lists (nested), numbered lists,
             markdown tables, code blocks, horizontal rules, body text.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = _build_styles()
    story = [Spacer(1, 0.3 * inch)]

    lines = markdown_text.splitlines()
    i = 0

    # Pending bullet / numbered list items collected before flushing
    pending_bullets: list[tuple[int, str]] = []    # (indent_level, text)
    pending_numbered: list[tuple[int, str]] = []   # (indent_level, text)
    in_code_block = False
    code_lines: list[str] = []
    table_lines: list[str] = []
    in_table = False

    def flush_bullets():
        if not pending_bullets:
            return
        items = []
        for lvl, txt in pending_bullets:
            s = styles['SubBullet'] if lvl > 0 else styles['Bullet']
            p = Paragraph(_inline_markup(txt), s)
            li = ListItem(p, leftIndent=12 + lvl * 12, bulletColor=colors.HexColor('#4A5568'))
            items.append(li)
        story.append(ListFlowable(
            items,
            bulletType='bullet',
            start='\u2022',
            bulletFontName='Helvetica',
            bulletFontSize=9,
            leftIndent=0,
            spaceBefore=2,
            spaceAfter=4,
        ))
        pending_bullets.clear()

    def flush_numbered():
        if not pending_numbered:
            return
        items = []
        for lvl, txt in pending_numbered:
            s = styles['SubBullet'] if lvl > 0 else styles['Bullet']
            p = Paragraph(_inline_markup(txt), s)
            li = ListItem(p, leftIndent=12 + lvl * 12)
            items.append(li)
        story.append(ListFlowable(
            items,
            bulletType='1',
            leftIndent=0,
            spaceBefore=2,
            spaceAfter=4,
        ))
        pending_numbered.clear()

    def flush_table():
        if not table_lines:
            return
        t = _parse_table(table_lines, styles)
        if t:
            story.append(Spacer(1, 6))
            story.append(t)
            story.append(Spacer(1, 10))
        table_lines.clear()

    def flush_code():
        if not code_lines:
            return
        joined = '\n'.join(code_lines)
        # Each line as a separate Code paragraph for proper spacing
        for cl in code_lines:
            safe = _sanitise_text(cl) if cl.strip() else ' '
            story.append(Paragraph(safe, styles['Code']))
        story.append(Spacer(1, 6))
        code_lines.clear()

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        # ── Code fence ──────────────────────────────────────────────────────
        if stripped.startswith('```'):
            if in_code_block:
                flush_bullets(); flush_numbered()
                flush_code()
                in_code_block = False
            else:
                flush_bullets(); flush_numbered(); flush_table()
                in_code_block = True
            i += 1
            continue

        if in_code_block:
            code_lines.append(line)
            i += 1
            continue

        # ── Horizontal rule ─────────────────────────────────────────────────
        if re.match(r'^[-*_]{3,}$', stripped):
            flush_bullets(); flush_numbered(); flush_table()
            story.append(Spacer(1, 4))
            story.append(HRFlowable(
                width='100%', thickness=0.5,
                color=colors.HexColor('#CBD5E0'), spaceAfter=4
            ))
            i += 1
            continue

        # ── Table row ───────────────────────────────────────────────────────
        if '|' in stripped and (stripped.startswith('|') or stripped.endswith('|')):
            flush_bullets(); flush_numbered()
            table_lines.append(line)
            in_table = True
            i += 1
            continue
        elif in_table:
            flush_table()
            in_table = False
            # fall through to process current line normally

        # ── Heading detection (handles lines without blank-line separation) ─
        heading_match = re.match(r'^(#{1,4})\s+(.*)', stripped)
        if heading_match:
            flush_bullets(); flush_numbered(); flush_table()
            level = len(heading_match.group(1))
            text = heading_match.group(2)
            style_map = {1: 'H1', 2: 'H2', 3: 'H3', 4: 'H4'}
            story.append(Paragraph(_inline_markup(text), styles[style_map.get(level, 'H4')]))
            i += 1
            continue

        # ── Bullet list ──────────────────────────────────────────────────────
        bullet_match = re.match(r'^(\s*)[-*]\s+(.*)', line)
        if bullet_match:
            flush_numbered()
            indent = len(bullet_match.group(1))
            level = indent // 2
            pending_bullets.append((level, bullet_match.group(2)))
            i += 1
            continue

        # ── Numbered list ────────────────────────────────────────────────────
        num_match = re.match(r'^(\s*)\d+[.)]\s+(.*)', line)
        if num_match:
            flush_bullets()
            indent = len(num_match.group(1))
            level = indent // 2
            pending_numbered.append((level, num_match.group(2)))
            i += 1
            continue

        # ── Blank line — flush pending lists ────────────────────────────────
        if stripped == '':
            flush_bullets()
            flush_numbered()
            flush_table()
            story.append(Spacer(1, 4))
            i += 1
            continue

        # ── Plain paragraph ──────────────────────────────────────────────────
        flush_bullets(); flush_numbered(); flush_table()
        story.append(Paragraph(_inline_markup(stripped), styles['Body']))
        story.append(Spacer(1, 2))
        i += 1

    # Flush anything remaining
    flush_bullets()
    flush_numbered()
    flush_table()
    flush_code()

    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    return buffer.getvalue()
