import io
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors

def header_footer(canvas, doc):
    """Draw the InvestAI branding header and a page number footer."""
    canvas.saveState()
    # Header
    canvas.setFont('Helvetica-Bold', 18)
    canvas.setFillColor(colors.HexColor('#FF4B2B'))
    canvas.drawString(doc.leftMargin, doc.pagesize[1] - 0.6 * inch, "InvestAI")
    
    canvas.setFont('Helvetica', 12)
    canvas.setFillColor(colors.gray)
    canvas.drawString(doc.leftMargin + 85, doc.pagesize[1] - 0.6 * inch, "| Agentic Stock Research")
    
    # Line under header
    canvas.setStrokeColor(colors.HexColor('#2D3748'))
    canvas.setLineWidth(1)
    canvas.line(doc.leftMargin, doc.pagesize[1] - 0.7 * inch, doc.pagesize[0] - doc.rightMargin, doc.pagesize[1] - 0.7 * inch)
    
    # Footer
    canvas.setFont('Helvetica', 9)
    page_num = canvas.getPageNumber()
    canvas.drawString(doc.leftMargin, 0.5 * inch, "Generated by InvestAI Platform")
    canvas.drawRightString(doc.pagesize[0] - doc.rightMargin, 0.5 * inch, f"Page {page_num}")
    canvas.restoreState()

def markdown_to_html_tags(text: str) -> str:
    """Convert basic markdown bold, italic, and code to ReportLab supported HTML-like tags."""
    # Bold
    text = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', text)
    # Italic
    text = re.sub(r'\*(.+?)\*', r'<i>\1</i>', text)
    # Inline code
    text = re.sub(r'`(.+?)`', r'<font face="Courier">\1</font>', text)
    # Escaped characters like & should be mapped properly but we leave them basic for now 
    # since ReportLab XML parser expects &amp;
    text = text.replace('&', '&amp;').replace('&amp;amp;', '&amp;')
    return text

def generate_pdf_report(markdown_text: str) -> bytes:
    """Generate a PDF document from markdown text with branding."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,      # Space for header
        bottomMargin=inch    # Space for footer
    )
    
    styles = getSampleStyleSheet()
    
    # Define custom styles mapping to standard fonts
    styles.add(ParagraphStyle(
        name='CustomH1', parent=styles['Heading1'], fontName='Helvetica-Bold', 
        fontSize=18, spaceBefore=16, spaceAfter=12, textColor=colors.HexColor('#1A202C')
    ))
    styles.add(ParagraphStyle(
        name='CustomH2', parent=styles['Heading2'], fontName='Helvetica-Bold', 
        fontSize=15, spaceBefore=14, spaceAfter=10, textColor=colors.HexColor('#2D3748')
    ))
    styles.add(ParagraphStyle(
        name='CustomH3', parent=styles['Heading3'], fontName='Helvetica-Bold', 
        fontSize=13, spaceBefore=12, spaceAfter=8, textColor=colors.HexColor('#4A5568')
    ))
    styles.add(ParagraphStyle(
        name='CustomBody', parent=styles['Normal'], fontName='Helvetica', 
        fontSize=11, spaceAfter=8, leading=15, textColor=colors.HexColor('#1A202C')
    ))
    styles.add(ParagraphStyle(
        name='CustomList', parent=styles['Normal'], fontName='Helvetica', 
        fontSize=11, spaceAfter=4, leading=15, textColor=colors.HexColor('#1A202C')
    ))
    
    story = []
    # Spacer to ensure first content avoids overlapping the header line
    story.append(Spacer(1, 0.3 * inch))
    
    blocks = markdown_text.split('\n\n')
    
    for block in blocks:
        block = block.strip()
        if not block:
            continue
            
        if block.startswith('# '):
            text = markdown_to_html_tags(block[2:])
            story.append(Paragraph(text, styles['CustomH1']))
        elif block.startswith('## '):
            text = markdown_to_html_tags(block[3:])
            story.append(Paragraph(text, styles['CustomH2']))
        elif block.startswith('### '):
            text = markdown_to_html_tags(block[4:])
            story.append(Paragraph(text, styles['CustomH3']))
        elif block.startswith('- ') or block.startswith('* '):
            # Process bullet lists
            items = block.split('\n')
            list_flowables = []
            for item in items:
                item = item.strip()
                if item.startswith('- '):
                    item = item[2:]
                elif item.startswith('* '):
                    item = item[2:]
                
                text = markdown_to_html_tags(item)
                bullet_p = Paragraph(text, styles['CustomList'])
                list_flowables.append(ListItem(bullet_p, leftIndent=15))
            
            story.append(ListFlowable(
                list_flowables, bulletType='bullet', start='bulletchar', bulletFontName='Helvetica'
            ))
            story.append(Spacer(1, 8))
        else:
            # Check for basic markdown table
            if '|' in block and '\n' in block:
                lines = block.split('\n')
                # A valid markdown table has a separator line with ---
                if len(lines) >= 3 and '|' in lines[0] and '|' in lines[1] and '-' in lines[1]:
                    data = []
                    for line in lines:
                        # Skip the separator line
                        if set(line.strip().replace('|', '').replace(':', '')) <= {'-', ' '}:
                            continue
                        
                        # Parse columns
                        # remove trailing/leading pipes if they exist
                        stripped = line.strip()
                        if stripped.startswith('|'): stripped = stripped[1:]
                        if stripped.endswith('|'): stripped = stripped[:-1]
                        
                        row = [markdown_to_html_tags(col.strip()) for col in stripped.split('|')]
                        # wrap in Paragraph for text wrapping
                        p_row = [Paragraph(cell, styles['CustomBody']) for cell in row]
                        data.append(p_row)
                    
                    if data:
                        # Table style
                        t = Table(data)
                        t.setStyle(TableStyle([
                            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#EDF2F7')),
                            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#1A202C')),
                            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                            ('VALIGN', (0,0), (-1,-1), 'TOP'),
                            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                            ('BOTTOMPADDING', (0,0), (-1,0), 8),
                            ('TOPPADDING', (0,0), (-1,0), 8),
                            ('BACKGROUND', (0,1), (-1,-1), colors.white),
                            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
                            ('TOPPADDING', (0,1), (-1,-1), 6),
                            ('BOTTOMPADDING', (0,1), (-1,-1), 6),
                        ]))
                        story.append(t)
                        story.append(Spacer(1, 12))
                        continue
            
            # Standard paragraph
            text = markdown_to_html_tags(block)
            # Support soft line breaks
            text = text.replace('\n', '<br/>')
            story.append(Paragraph(text, styles['CustomBody']))
            
    # Build PDF
    doc.build(story, onFirstPage=header_footer, onLaterPages=header_footer)
    
    return buffer.getvalue()
